name: To Tencent Cos & Push to gh-pages

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository master branch
        uses: actions/checkout@v2
        with:
          ref: "master"
          submodules: true
      # from: https://github.com/actions/setup-node

      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: "14.x"

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache

      - name: Install Dependencies
        run: npm install

      - name: Replace hexo-asset-image index.js
        run: cp ./node_modules_tmp/hexo-asset-image-index.js ./node_modules/hexo-asset-image/index.js

      - name: Build for gitio
        run: npm run clean && npm run build-gitio

      - name: Deploy to gitio
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.HEXO_DEPLOY_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages # deploying branch
      
      - name: Build for Tencent COS
        run: npm run clean && npm run build-tencentcos

      - name: Install Tencent COSCMD
        run: sudo pip install coscmd

      - name: Configure Tencent COSCMD
        env:
          SECRET_ID: ${{ secrets.SECRET_ID }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          BUCKET: ${{ secrets.BUCKET }}
          REGION: ap-nanjing
        run: coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION

      - name: Clean current Bucket
        run: coscmd delete -rf /

      - name: Uplode to Tencent COS
        run: cd ./public && coscmd upload -r ./ /
