name: To Tencent Cos

on:
    push:
        branches: [ master, gh-pages, luxiaolululu-patch-1 ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository master branch
          uses: actions/checkout@v2
          with: 
              ref: 'master'
              submodules: true
        # from: https://github.com/actions/setup-node
        - name: Copy config yml to theme 
          run: cp theme_config.yml themes/yilia/_config.yml
        
        - name: Setup Node.js
          uses: actions/setup-node@master
          with: 
              node-version: "14.x"

        - name: Install Dependencies
          run: npm install

        ## generate files
        - name: Generate Hexo Site Public Files & Create Files for Blog Assets
          run: npm deploy
        
        - name: Install Tencent COSCMD
          run: sudo pip install coscmd
        
        - name: Configure Tencent COSCMD
          env:
              SECRET_ID: ${{ secrets.SECRET_ID }}
              SECRET_KEY: ${{ secrets.SECRET_KEY }}
              BUCKET: ${{ secrets.BUCKET }}
              REGION: ap-nanjing
          run: coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION
        
        - name: Debug1
          run: pwd
        
        - name: Debug2
          run: ls
        
        - name: Clean current Bucket
          run: coscmd delete -rf /
        
        - name: Uplode to Tencent COS
          run: coscmd upload -r ./public / --ignore "./.git/*","./.github/*"
