name: To Tencent Cos

on:
  push:
    branches: [ gh-pages ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Tencent COSCMD
        run: sudo pip install coscmd
      - name: Debug1
        run: pwd
      - name: Debug2
        run: ls
      - name: Configure Tencent COSCMD
        env:
          SECRET_ID: ${{ secrets.SECRET_ID }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          BUCKET: ${{ secrets.BUCKET }}
          REGION: ap-nanjing
        run: coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION
      - name: Clean current Bucket
        run: coscmd delete -rf /
      - name: Uplode to Tencent COS
        run: coscmd upload -r ./ / --ignore "./.git/*","./.github/*"
